[workspace]
resolver = "3"
members = ["alphacou", "engine", "minicou", "py", "wasm"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
rand = "0.9"

[profile.release]
# https://fasterthanli.me/articles/why-is-my-rust-build-so-slow
debug = 1
