[package]
name = "ascacou-python"
version = "0.3.1"
edition.workspace = true

[lib]
name = "ascacou"
crate-type = ["cdylib"]

[dependencies]
ascacou.workspace = true
pyo3 = { version = "0.27", features = ["extension-module"] }
