[package]
name = "minicou"
description = "A (some day strong) minimax solver for the ascacou board game"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "minicou"
path = "src/bin/cli.rs"

[dependencies]
ascacou.workspace = true
clap.workspace = true
